import fs from 'node:fs';
import {productVisual} from './product-visual.js';
const company=JSON.parse(fs.readFileSync('content/company.json'));
const features=JSON.parse(fs.readFileSync('content/verified-features.json')).filter(f=>f.public&&f.verified);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const form=fs.readFileSync('content/contact-form.html','utf8');
const nav=[['/product','Product'],['/workflow','How it works'],['/deployment','Deploy'],['/downloads','Downloads'],['/trial','Get trial'],['/about','About us'],['/contact','Contact']];
const descriptions=Object.fromEntries(features.map(f=>[f.id,f.description]));
const buttons=features.map((f,i)=>'<button class="workflow-tab" data-flow="'+f.id+'" data-description="'+esc(f.description)+'" aria-pressed="'+(i===0)+'"><span>0'+(i+1)+'</span>'+esc(f.name)+'</button>').join('');
const board=productVisual();
function page(key,title,description,body){
const route=key==='index'?'/':'/'+key;
const structured=JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:company.displayName,url:'__SITE_URL__',logo:'__SITE_URL__/assets/evision-square.png',email:company.salesEmail}).replaceAll('<','\\u003c');
return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | ${esc(company.displayName)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="__SITE_URL__${route}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="__SITE_URL__${route}"><meta property="og:image" content="__SITE_URL__/assets/evision-square.png"><meta property="og:type" content="website"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><link rel="icon" href="/assets/evision-square.png"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/design.css"><script src="/runtime-config.js" defer></script><script type="module" src="/app.js"></script>${['index','product','workflow'].includes(key)?'<script type="module" src="/workflow.js"></script>':''}${key==='index'?'<script type="module" src="/hero-scene.js"></script>':''}<script type="application/ld+json">${structured}</script></head><body class="marketing page-${key}"><a class="skip" href="#main">Skip to content</a><header class="header"><a class="brand" href="/" aria-label="E-Vision India home"><img src="/assets/evision-horizontal.png" alt="Evision" width="233" height="216"></a><nav aria-label="Main navigation">${nav.map(([url,label])=>`<a href="${url}" ${route===url?'aria-current="page"':''}>${label}</a>`).join('')}</nav><button id="menu" class="menu" aria-label="Open navigation" aria-expanded="false">☰</button></header><main id="main">${body}</main><footer class="wrap footer"><div class="footer-top"><a class="brand" href="/" aria-label="E-Vision India home"><img src="/assets/evision-horizontal.png" alt="Evision" width="233" height="216" loading="lazy"></a><p>${esc(company.tagline)}</p><a href="mailto:${company.salesEmail}">${company.salesEmail} ↗</a></div><div class="footer-bottom"><span>© ${new Date().getUTCFullYear()} ${esc(company.displayName)}</span>${nav.map(([url,label])=>`<a href="${url}">${label}</a>`).join('')}<a href="/privacy">Privacy</a><a href="/owner">Owner sign-in</a></div></footer></body></html>`;
}
const heading=(k,t,p='')=>'<section class="wrap page-heading"><p class="eyebrow">'+k+'</p><h1>'+t+'</h1>'+(p?'<p class="intro">'+p+'</p>':'')+'</section>';
const chooser='<div class="workflow-tabs" role="group" aria-label="Explore E-VMS workflow">'+buttons+'</div><p id="workflow-description" aria-live="polite">'+descriptions.organize+'</p>';
const pages={
index:['E-VMS video management','Organize cameras, allocate recording storage, review footage and manage access with E-VMS.',`<section class="home-hero"><div class="wrap hero-shell"><div class="hero-copy"><p class="eyebrow"><span class="dot"></span>E-VISION INDIA PRESENTS</p><h1>Video,<br><span>under control.</span></h1><p class="intro">E-VMS brings camera organization, recording storage, playback and user access into one operator workflow.</p><div class="actions"><a class="button" href="/contact#demo">Request a demo <span>↗</span></a><a class="text-link" href="/product">Explore the product →</a></div><div class="hero-proof"><span>01 Organize</span><span>02 Record</span><span>03 Review</span><span>04 Manage</span></div></div><div class="hero-visual"><canvas id="evms-3d" aria-label="Interactive 3D visualization of a security camera"></canvas><div class="hero-orbit"><span>INTERACTIVE</span><b>3D</b><span>PRODUCT VISUAL</span></div><p>Move your pointer to explore</p></div></div></section><section class="signal-strip"><div class="wrap"><span>CAMERA NETWORK</span><i></i><span>RECORDING PATH</span><i></i><span>PLAYBACK</span><i></i><span>CONTROLLED ACCESS</span></div></section><section class="wrap manifesto"><p class="eyebrow">BUILT AROUND THE OPERATOR</p><h2>See the system.<br><span>Act with context.</span></h2><p>From a grouped camera tree to a selected playback range, E-VMS keeps each task connected to the site and user performing it.</p></section><section class="wrap showcase"><div class="showcase-head"><p class="eyebrow">INTERACTIVE PRODUCT WALKTHROUGH</p><h2>Four tasks. One workspace.</h2></div>${board}<div class="workflow-explorer">${chooser}</div></section><section class="brand-story"><div class="brand-art"><img src="/assets/evms-artwork.png" alt="E-VMS product artwork"></div><div class="brand-copy"><p class="eyebrow">E-VMS / E-VISION INDIA</p><h2>Made for<br>smarter spaces.</h2><p>${esc(company.description)}</p><a class="text-link" href="/about">About E-Vision India →</a></div></section><section class="wrap closing"><p class="eyebrow">START WITH YOUR SITE</p><h2>Your cameras. Your storage.<br>Your requirements.</h2><div><a class="button" href="/contact">Talk to E-Vision ↗</a><a class="text-link" href="/deployment">Plan a deployment →</a></div></section>`],
product:['E-VMS capabilities','Verified camera organization, recording, playback and user management capabilities.',heading('THE PRODUCT / E-VMS','Your video network.<br><span>A connected workflow.</span>','Explore the everyday work of organizing cameras, recording to allocated storage, reviewing footage and managing access.')+`<section class="wrap showcase">${board}<div class="workflow-explorer">${chooser}</div></section><section class="wrap feature-section"><div class="section-intro"><p class="eyebrow">WHAT E-VMS DOES</p><h2>Capabilities, with context.</h2></div><div id="features" class="feature-grid" aria-live="polite"><p>Product information is temporarily unavailable. Enable JavaScript or reload to retry.</p></div><noscript><p>Contact our team for a product walkthrough.</p></noscript></section><section class="wrap bottom-cta"><h2>Explore it with your team.</h2><a class="button" href="/contact#demo">Request a demo ↗</a></section>`],
workflow:['How E-VMS works','Follow the E-VMS workflow from camera organization to recording, playback and access management.',heading('HOW IT WORKS','From camera network<br><span>to recorded evidence.</span>')+`<section class="wrap workflow-page">${board}${chooser}</section><section class="wrap workflow-details">${features.map((f,i)=>'<article><p class="eyebrow">0'+(i+1)+'</p><h2>'+esc(f.name)+'</h2><p>'+esc(f.description)+'</p><small>'+esc(f.limitation)+'</small></article>').join('')}</section>`],
deployment:['Deploy E-VMS','Plan an E-VMS backend, desktop clients and accessible recording storage paths.',heading('DEPLOYMENT','Your cameras.<br><span>Your recording destinations.</span>','Plan the E-VMS backend, operator access and storage before installing a desktop client.')+`<section class="wrap deployment-grid"><article><p class="eyebrow">01 / APPLICATION</p><h2>Connect to an E-VMS backend.</h2><p>The Windows desktop applications connect to an existing E-VMS backend. Installing a client alone does not provide the complete recording system.</p></article><article><p class="eyebrow">02 / STORAGE</p><h2>Allocate a recording path.</h2><p>Storage must be mounted, reachable and writable from the recorder. Validate the path, allocate cameras and explicitly start recording.</p><p>A recording destination is configured storage. There is no separate E-VMS Recording Agent.</p></article><article><p class="eyebrow">03 / ACCESS</p><h2>Define who can use it.</h2><p>Apply user roles and site/camera permissions. Match access to each operator’s responsibilities.</p></article></section><section class="wrap bottom-cta"><h2>Check your deployment requirements.</h2><a class="button" href="/contact">Talk to our team ↗</a></section>`],
about:['About E-Vision India','Company and product information for E-Vision India and E-VMS.',heading('COMPANY / E-VISION INDIA','Your security.<br><span>Our priority.</span>')+`<section class="wrap about-grid"><div class="company-mark"><img src="/assets/evision-square.png" alt="Evision — Your security our priority" width="200" height="200"></div><div><p class="eyebrow">E-VISION INDIA / E-VMS</p><h2>Video management,<br>from organization to review.</h2><p>${esc(company.description)}</p><p>Contact our team to discuss camera organization, storage allocation and operator access for your deployment.</p><a class="button" href="/contact">Contact us ↗</a></div></section>`],
contact:['Contact E-Vision India','Sales, technical support and licence enquiries for E-VMS.',heading('CONTACT / DEMO','Tell us about<br><span>your deployment.</span>')+`<section class="wrap contact-grid" id="demo"><aside><h2>Contact E-Vision India.</h2><p>Request a product walkthrough or discuss your cameras, recording requirements and operator workflow.</p><div class="contact-detail"><span>SALES & PRODUCT ENQUIRIES</span><a href="mailto:${company.salesEmail}">${company.salesEmail} ↗</a></div><div class="contact-detail"><span>TECHNICAL SUPPORT</span><a href="mailto:${company.supportEmail}">${company.supportEmail} ↗</a><br><a href="tel:${company.supportPhone}">${company.supportPhone}</a></div><div class="contact-detail"><span>LICENCE ENQUIRIES</span><a href="tel:${company.licensePhone}">${company.licensePhone}</a></div><p class="footnote">Please don’t send passwords, camera credentials or sensitive footage.</p></aside><div class="contact-form"><h2>Request a demo</h2>${form}<noscript>JavaScript is required to submit this form. You can email our sales team instead.</noscript></div></section>`],
downloads:['E-VMS releases and downloads','Latest and historical mirrored E-VMS Windows installer releases.',heading('RELEASES / DOWNLOADS','E-VMS installers.<br><span>Release by release.</span>','Choose an installer and review what changed before updating.')+`<section class="wrap download-page"><div id="release" class="release-box" aria-live="polite"><p>Release information temporarily unavailable. Enable JavaScript or reload to retry.</p></div><noscript><p>JavaScript is needed to check release information.</p></noscript><div class="download-help"><h2>Before you install</h2><p>Windows x64 installers require an existing E-VMS backend. Downloads are served from the website’s mirrored GitHub releases. Availability is shown from retrieved release metadata.</p><p>A downloadable artifact is not automatically a production-signed build. Review its release manifest, SHA-256 and Authenticode status before deployment; unsigned verification builds are not production eligible.</p><a class="text-link" href="/contact">Need help? Contact us ↗</a></div></section>`],
privacy:['Demo request privacy','How E-VMS website enquiry information is used.',heading('PRIVACY','Your enquiry<br><span>and your information.</span>')+`<section class="wrap privacy"><p>The enquiry form collects name, company, email, optional phone, interest, contact preference, message and source page so ${esc(company.displayName)} can respond.</p><h2>Storage and delivery</h2><p>The private website database is the system of record. When configured, daily reports may be emailed to the sales team and approved fields synchronized to a private Google Sheet. Delivery is not guaranteed by submitting the form.</p><h2>Retention and requests</h2><p>Requests are retained for follow-up under the deployment’s retention policy. Reports do not delete requests automatically. For access, correction or deletion requests, email <a href="mailto:${company.salesEmail}">${company.salesEmail}</a>.</p><h2>Cookies</h2><p>Owner sign-in uses an essential session cookie. Rate limits use short-lived hashed network identifiers. No advertising trackers are included.</p><h2>What not to send</h2><p>Do not submit device credentials, passwords, identity documents, payment information or sensitive footage.</p><h2>External downloads</h2><p>GitHub applies its own terms to release pages and downloads.</p><a class="button" href="/contact#demo">Back to enquiry form ↗</a></section>`]
};
for(const [key,[title,description,body]] of Object.entries(pages))fs.writeFileSync('public/'+key+'.html',page(key,title,description,body));
